Retrieve sample list from cms-project-relval page

diff --git a/Validation/Tools/makeValidation b/Validation/Tools/makeValidation
--- a/Validation/Tools/makeValidation
+++ b/Validation/Tools/makeValidation
@@ -2,6 +2,7 @@
 
 if [ $# == 0 ]; then
   echo "Usage : $0 CMSSW_VERSION [CMSSW_VERSION2 CMSSW_VERSION3 ...]"
+  echo " Set environment variable NOSUBMIT not to automatically submit jobs to LSF"
   exit
 fi
 
@@ -12,7 +13,7 @@ if [ ! -d $RUNTIMEDIR ]; then
   mkdir $RUNTIMEDIR
 fi
 
-echo "@@@ Checking DBS tools @@@"
+echo "@@ Checking DBS tools @@"
 if [ ! -x $RUNTIMEDIR/tool_ls ]; then
   wget --no-check-certificate https://cmsweb.cern.ch/dbs_discovery/tool_ls -O $RUNTIMEDIR/tool_ls
   chmod +x $RUNTIMEDIR/tool_ls
@@ -23,27 +24,45 @@ if [ ! -x $RUNTIMEDIR/dbssql ]; then
   chmod +x $RUNTIMEDIR/dbssql
 fi
 
-echo "@@@ Preparing configuration files @@@"
 for CMSSW_VERSION in $@; do
-  echo "@@@@ Set up workarea for $CMSSW_VERSION @@@"
+  echo "@@ Preparing configuration files for $CMSSW_VERSION @@"
+  echo "@@@ Checking dataset list file @@@"
+  if [ ! -f ${CMSSW_VERSION}.txt ]; then
+    echo "@@@@ No dataset list. retrieving dataset list @@@@"
+    curl http://cms-project-relval.web.cern.ch/cms-project-relval/relval_stats/${CMSSW_VERSION}.txt | \
+      grep GEN-SIM-RECO | awk -F'|' '{print $2}' | sed -e 's#/GEN-SIM-RECO##g' > ${CMSSW_VERSION}.txt
+    if [ $? != 0 ]; then
+      echo "@@@@@ Cannot retrive relval dataset list @@@@@"
+      continue
+    fi
+    vi ${CMSSW_VERSION}.txt
+  fi
+  DATASETS=`cat ${CMSSW_VERSION}.txt`
 
-  scram project CMSSW $CMSSW_VERSION
+  echo "@@@ Set up workarea for $CMSSW_VERSION @@@"
 
   if [ ! -d $CMSSW_VERSION ]; then
-    echo "@@@@ Cannot find $CMSSW_VERSION @@@@"
+    scram project CMSSW $CMSSW_VERSION
+  fi
+
+  ## Print error message if scram project fails to set up workarea
+  if [ ! -d $CMSSW_VERSION ]; then
+    echo "@@@@ Cannot set up project area for $CMSSW_VERSION @@@@"
     continue
   fi
 
   cd $CMSSW_VERSION/src
   eval `scram runtime -sh`
 
-  cvs co -d Validation/RPCRecHits UserCode/JHGoh/Validation/RPCRecHits
+  if [ ! -d Validation/RPCRecHits ]; then
+    cvs co -d Validation/RPCRecHits UserCode/JHGoh/Validation/RPCRecHits
+  fi
   scram build
 
   cd Validation/RPCRecHits/test
 
   # Make bsub-run script
-  echo "@@@@ Preparing submission script @@@@"
+  echo "@@@ Preparing submission script @@@"
   cat > run.sh <<EOF
 #!/bin/bash
 
@@ -53,23 +72,26 @@ eval \`scram runtime -sh\`
 EOF
   chmod +x run.sh
 
-  echo "@@@@ Preparing sample file list configuration fragments @@@@"
+  echo "@@ Preparing sample cff files @@"
+  rm -rf samples
   mkdir samples
 
-  for DATASETNAME in RelValSingleMuPt10 RelValSingleMuPt100 RelValSingleMuPt1000; do
-    DBSQUERY_PREFIX="find dataset where release = $CMSSW_VERSION and dataset like /$DATASETNAME"
+  for DATASET in $DATASETS; do
+    DATASETNAME=`echo $DATASET | cut -d/ -f 2`
+
+    DBSQUERY_PREFIX="find dataset where release = $CMSSW_VERSION and dataset like $DATASET"
     
-    DATASET_SIM=`$RUNTIMEDIR/dbssql --input="$DBSQUERY_PREFIX/*/GEN-SIM-DIGI-RAW-HLTDEBUG" | grep -o "'/RelVal.*'" | head -1`
-    DATASET_REC=`$RUNTIMEDIR/dbssql --input="$DBSQUERY_PREFIX/*/GEN-SIM-RECO" | grep -o "'/RelVal.*'" | head -1`
+    DATASET_SIM=`$RUNTIMEDIR/dbssql --input="$DBSQUERY_PREFIX/GEN-SIM-DIGI-RAW-HLTDEBUG" | grep -o "'/RelVal.*'" | head -1`
+    DATASET_REC=`$RUNTIMEDIR/dbssql --input="$DBSQUERY_PREFIX/GEN-SIM-RECO" | grep -o "'/RelVal.*'" | head -1`
 
     # Prepare source-cfg files
     if [ X$DATASET_SIM == X ]; then
-      echo "No GEN-SIM-DIGI-RAW-HLTDEBUG dataset found"
+      echo "No $DATASET found"
       continue
     fi
 
     if [ X$DATASET_REC == X ]; then
-      echo "No GEN-SIM-RECO dataset found"
+      echo "No $DATASET found"
       continue
     fi
 
@@ -107,11 +129,16 @@ EOF
 
   done
 
-  echo "@@@@ Finished Validation environment setup for $CMSSW_VERSION @@@@"
+  echo "@@@ Finished Validation environment setup for $CMSSW_VERSION @@@"
 
-  echo "@@@ Submitting jobs @@@"
-  #bsub -q 8nh run.sh
+  if [ _$NOSUBMIT == _ && -x /usr/bin/bsub ]; then
+    echo "@@@ Submitting jobs @@@"
+    bsub -q 8nh run.sh
+  fi
 
   cd $BASEDIR
-  echo "@@@ Finished @@@"
+  echo "@@ Finished $CMSSW_VERSION @@"
 done
+
+bjobs
+echo "@@ All done! @@"
